# Generated by Django 3.0.6 on 2020-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='intended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
