# Generated by Django 3.0.6 on 2020-06-11 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200610_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='intended_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
