# Generated by Django 3.0.6 on 2020-06-07 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(default=datetime.datetime.now)),
                ('intended_date', models.DateField(default=datetime.date.today)),
                ('earth', models.IntegerField()),
                ('water', models.IntegerField()),
                ('air', models.IntegerField()),
                ('fire', models.IntegerField()),
            ],
        ),
    ]
